export const dummyAccounts = [
    {
        "id": "#MSLI-2025",
        "firstName": "Marcus",
        "lastName": "Pilapil",
        "email": "mpilapil@techfactors.com",
        "phoneNo": "+639111111111",
        "username": "mpilapil",
        "department": "ETS",
        "role": "Employee",
    },
    {
        "id": "#PZJN-2025",
        "firstName": "Prinz",
        "lastName": "Julian",
        "email": "pjulian@techfactors.com",
        "phoneNo": "+639222222222",
        "username": "pjulian",
        "department": "ETS",
        "role": "Employee",
    },
    {
        "id": "#LECN-2025",
        "firstName": "Lanze",
        "lastName": "Conanan",
        "email": "lconanan@techfactors.com",
        "phoneNo": "+639333333333",
        "username": "lconanan",
        "department": "ETS",
        "role": "Employee",
    },
    {
        "id": "#EEGA-2025",
        "firstName": "Elle",
        "lastName": "Gaza",
        "email": "egaza@techfactors.com",
        "phoneNo": "+639444444444",
        "username": "egaza",
        "department": "ETS",
        "role": "HR",
    },
    {
        "id": "#ANHZ-2021",
        "firstName": "Angel",
        "lastName": "Hernandez",
        "email": "ahernandez@techfactors.com",
        "phoneNo": "+639555555555",
        "username": "ahernandez",
        "department": "ETS",
        "role": "Employee",
    },
]