export const dummyData = [
  {
    "id": 1,
    "firstName": "Felicia",
    "lastName": "Salazar",
    "email": "felicia.salazar1@techfactors.com",
    "phone": "09171205873",
    "username": "felicia.salazar",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 2,
    "firstName": "Nathan",
    "lastName": "Torres",
    "email": "nathan.torres2@techfactors.com",
    "phone": "09627291140",
    "username": "nathan.torres",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 3,
    "firstName": "Elizabeth",
    "lastName": "Ellis",
    "email": "elizabeth.ellis3@techfactors.com",
    "phone": "09190867874",
    "username": "elizabeth.ellis",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 4,
    "firstName": "Isaac",
    "lastName": "Elliott",
    "email": "isaac.elliott4@techfactors.com",
    "phone": "09160789807",
    "username": "isaac.elliott",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 5,
    "firstName": "William",
    "lastName": "Miller",
    "email": "william.miller5@techfactors.com",
    "phone": "09218786984",
    "username": "william.miller",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 6,
    "firstName": "Jessica",
    "lastName": "Miller",
    "email": "jessica.miller6@techfactors.com",
    "phone": "09155410837",
    "username": "jessica.miller",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 7,
    "firstName": "Chelsea",
    "lastName": "Estrada",
    "email": "chelsea.estrada7@techfactors.com",
    "phone": "09780520905",
    "username": "chelsea.estrada",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 8,
    "firstName": "Curtis",
    "lastName": "Stevens",
    "email": "curtis.stevens8@techfactors.com",
    "phone": "09804628646",
    "username": "curtis.stevens",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 9,
    "firstName": "Dean",
    "lastName": "Howard",
    "email": "dean.howard9@techfactors.com",
    "phone": "09811375426",
    "username": "dean.howard",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 10,
    "firstName": "David",
    "lastName": "Crawford",
    "email": "david.crawford10@techfactors.com",
    "phone": "09715978843",
    "username": "david.crawford",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 11,
    "firstName": "Dylan",
    "lastName": "Edwards",
    "email": "dylan.edwards11@techfactors.com",
    "phone": "09894346031",
    "username": "dylan.edwards",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 12,
    "firstName": "Mary",
    "lastName": "Green",
    "email": "mary.green12@techfactors.com",
    "phone": "09917738128",
    "username": "mary.green",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 13,
    "firstName": "Kelly",
    "lastName": "Cooper",
    "email": "kelly.cooper13@techfactors.com",
    "phone": "09397055715",
    "username": "kelly.cooper",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 14,
    "firstName": "Victor",
    "lastName": "Wagner",
    "email": "victor.wagner14@techfactors.com",
    "phone": "09956162171",
    "username": "victor.wagner",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 15,
    "firstName": "Danielle",
    "lastName": "Kirk",
    "email": "danielle.kirk15@techfactors.com",
    "phone": "09079866697",
    "username": "danielle.kirk",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 16,
    "firstName": "Michelle",
    "lastName": "Romero",
    "email": "michelle.romero16@techfactors.com",
    "phone": "09143633578",
    "username": "michelle.romero",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 17,
    "firstName": "Amber",
    "lastName": "Evans",
    "email": "amber.evans17@techfactors.com",
    "phone": "09010906030",
    "username": "amber.evans",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 18,
    "firstName": "Christina",
    "lastName": "Bass",
    "email": "christina.bass18@techfactors.com",
    "phone": "09991797781",
    "username": "christina.bass",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 19,
    "firstName": "Lisa",
    "lastName": "Obrien",
    "email": "lisa.obrien19@techfactors.com",
    "phone": "09219020491",
    "username": "lisa.obrien",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 20,
    "firstName": "James",
    "lastName": "Bennett",
    "email": "james.bennett20@techfactors.com",
    "phone": "09409206685",
    "username": "james.bennett",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 21,
    "firstName": "Shirley",
    "lastName": "Day",
    "email": "shirley.day21@techfactors.com",
    "phone": "09367631236",
    "username": "shirley.day",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 22,
    "firstName": "Cynthia",
    "lastName": "Delacruz",
    "email": "cynthia.delacruz22@techfactors.com",
    "phone": "09781774636",
    "username": "cynthia.delacruz",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 23,
    "firstName": "Christina",
    "lastName": "White",
    "email": "christina.white23@techfactors.com",
    "phone": "09444318100",
    "username": "christina.white",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 24,
    "firstName": "Cynthia",
    "lastName": "Valdez",
    "email": "cynthia.valdez24@techfactors.com",
    "phone": "09051913593",
    "username": "cynthia.valdez",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 25,
    "firstName": "Michael",
    "lastName": "Nguyen",
    "email": "michael.nguyen25@techfactors.com",
    "phone": "09809109164",
    "username": "michael.nguyen",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 26,
    "firstName": "Julie",
    "lastName": "Pineda",
    "email": "julie.pineda26@techfactors.com",
    "phone": "09061041587",
    "username": "julie.pineda",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 27,
    "firstName": "Jill",
    "lastName": "Thompson",
    "email": "jill.thompson27@techfactors.com",
    "phone": "09015174653",
    "username": "jill.thompson",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 28,
    "firstName": "Kelly",
    "lastName": "Delgado",
    "email": "kelly.delgado28@techfactors.com",
    "phone": "09767346223",
    "username": "kelly.delgado",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 29,
    "firstName": "Brittany",
    "lastName": "Ross",
    "email": "brittany.ross29@techfactors.com",
    "phone": "09610406714",
    "username": "brittany.ross",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 30,
    "firstName": "Joseph",
    "lastName": "Allen",
    "email": "joseph.allen30@techfactors.com",
    "phone": "09482725382",
    "username": "joseph.allen",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 31,
    "firstName": "Brett",
    "lastName": "Velasquez",
    "email": "brett.velasquez31@techfactors.com",
    "phone": "09924079798",
    "username": "brett.velasquez",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 32,
    "firstName": "Matthew",
    "lastName": "Allen",
    "email": "matthew.allen32@techfactors.com",
    "phone": "09489547278",
    "username": "matthew.allen",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 33,
    "firstName": "Kevin",
    "lastName": "Jennings",
    "email": "kevin.jennings33@techfactors.com",
    "phone": "09402676946",
    "username": "kevin.jennings",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 34,
    "firstName": "Susan",
    "lastName": "Campbell",
    "email": "susan.campbell34@techfactors.com",
    "phone": "09444538601",
    "username": "susan.campbell",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 35,
    "firstName": "Shannon",
    "lastName": "Baker",
    "email": "shannon.baker35@techfactors.com",
    "phone": "09048444506",
    "username": "shannon.baker",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 36,
    "firstName": "Samuel",
    "lastName": "Martinez",
    "email": "samuel.martinez36@techfactors.com",
    "phone": "09450721269",
    "username": "samuel.martinez",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 37,
    "firstName": "Douglas",
    "lastName": "Herrera",
    "email": "douglas.herrera37@techfactors.com",
    "phone": "09445672494",
    "username": "douglas.herrera",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 38,
    "firstName": "Donna",
    "lastName": "Zamora",
    "email": "donna.zamora38@techfactors.com",
    "phone": "09650622952",
    "username": "donna.zamora",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 39,
    "firstName": "Eddie",
    "lastName": "Palmer",
    "email": "eddie.palmer39@techfactors.com",
    "phone": "09561850243",
    "username": "eddie.palmer",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 40,
    "firstName": "Jerry",
    "lastName": "Rivera",
    "email": "jerry.rivera40@techfactors.com",
    "phone": "09951998792",
    "username": "jerry.rivera",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 41,
    "firstName": "Christopher",
    "lastName": "Smith",
    "email": "christopher.smith41@techfactors.com",
    "phone": "09280436205",
    "username": "christopher.smith",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 42,
    "firstName": "John",
    "lastName": "Murphy",
    "email": "john.murphy42@techfactors.com",
    "phone": "09172027288",
    "username": "john.murphy",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 43,
    "firstName": "Joel",
    "lastName": "Young",
    "email": "joel.young43@techfactors.com",
    "phone": "09521940703",
    "username": "joel.young",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 44,
    "firstName": "Catherine",
    "lastName": "Gonzalez",
    "email": "catherine.gonzalez44@techfactors.com",
    "phone": "09842782567",
    "username": "catherine.gonzalez",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 45,
    "firstName": "Nancy",
    "lastName": "Fletcher",
    "email": "nancy.fletcher45@techfactors.com",
    "phone": "09167631497",
    "username": "nancy.fletcher",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 46,
    "firstName": "Lisa",
    "lastName": "Williams",
    "email": "lisa.williams46@techfactors.com",
    "phone": "09365616121",
    "username": "lisa.williams",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 47,
    "firstName": "Stephanie",
    "lastName": "Evans",
    "email": "stephanie.evans47@techfactors.com",
    "phone": "09867946426",
    "username": "stephanie.evans",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 48,
    "firstName": "Lindsey",
    "lastName": "Washington",
    "email": "lindsey.washington48@techfactors.com",
    "phone": "09339136275",
    "username": "lindsey.washington",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 49,
    "firstName": "Brett",
    "lastName": "Turner",
    "email": "brett.turner49@techfactors.com",
    "phone": "09376161352",
    "username": "brett.turner",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 50,
    "firstName": "Rachel",
    "lastName": "Rowland",
    "email": "rachel.rowland50@techfactors.com",
    "phone": "09947676729",
    "username": "rachel.rowland",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 51,
    "firstName": "Jesse",
    "lastName": "Velasquez",
    "email": "jesse.velasquez51@techfactors.com",
    "phone": "09922214785",
    "username": "jesse.velasquez",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 52,
    "firstName": "Mark",
    "lastName": "Hopkins",
    "email": "mark.hopkins52@techfactors.com",
    "phone": "09895548182",
    "username": "mark.hopkins",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 53,
    "firstName": "Rebecca",
    "lastName": "Rocha",
    "email": "rebecca.rocha53@techfactors.com",
    "phone": "09639953084",
    "username": "rebecca.rocha",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 54,
    "firstName": "Jorge",
    "lastName": "Nguyen",
    "email": "jorge.nguyen54@techfactors.com",
    "phone": "09241674431",
    "username": "jorge.nguyen",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 55,
    "firstName": "Christina",
    "lastName": "Duran",
    "email": "christina.duran55@techfactors.com",
    "phone": "09999722236",
    "username": "christina.duran",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 56,
    "firstName": "Jacob",
    "lastName": "Kim",
    "email": "jacob.kim56@techfactors.com",
    "phone": "09467777841",
    "username": "jacob.kim",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 57,
    "firstName": "Ashley",
    "lastName": "Silva",
    "email": "ashley.silva57@techfactors.com",
    "phone": "09140537831",
    "username": "ashley.silva",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 58,
    "firstName": "Kenneth",
    "lastName": "Hansen",
    "email": "kenneth.hansen58@techfactors.com",
    "phone": "09781187058",
    "username": "kenneth.hansen",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 59,
    "firstName": "Mitchell",
    "lastName": "Schwartz",
    "email": "mitchell.schwartz59@techfactors.com",
    "phone": "09957183048",
    "username": "mitchell.schwartz",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 60,
    "firstName": "Ryan",
    "lastName": "Benton",
    "email": "ryan.benton60@techfactors.com",
    "phone": "09469934712",
    "username": "ryan.benton",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 61,
    "firstName": "William",
    "lastName": "Gutierrez",
    "email": "william.gutierrez61@techfactors.com",
    "phone": "09123615527",
    "username": "william.gutierrez",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 62,
    "firstName": "Nicolas",
    "lastName": "Jones",
    "email": "nicolas.jones62@techfactors.com",
    "phone": "09859827212",
    "username": "nicolas.jones",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 63,
    "firstName": "Jason",
    "lastName": "Baker",
    "email": "jason.baker63@techfactors.com",
    "phone": "09881192811",
    "username": "jason.baker",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 64,
    "firstName": "Eric",
    "lastName": "Buchanan",
    "email": "eric.buchanan64@techfactors.com",
    "phone": "09504135002",
    "username": "eric.buchanan",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 65,
    "firstName": "Brian",
    "lastName": "Thomas",
    "email": "brian.thomas65@techfactors.com",
    "phone": "09776811305",
    "username": "brian.thomas",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 66,
    "firstName": "Timothy",
    "lastName": "Dennis",
    "email": "timothy.dennis66@techfactors.com",
    "phone": "09007529107",
    "username": "timothy.dennis",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 67,
    "firstName": "Michelle",
    "lastName": "Cain",
    "email": "michelle.cain67@techfactors.com",
    "phone": "09364788532",
    "username": "michelle.cain",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 68,
    "firstName": "Robert",
    "lastName": "Miller",
    "email": "robert.miller68@techfactors.com",
    "phone": "09924365240",
    "username": "robert.miller",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 69,
    "firstName": "Omar",
    "lastName": "Ford",
    "email": "omar.ford69@techfactors.com",
    "phone": "09959836505",
    "username": "omar.ford",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 70,
    "firstName": "Jaime",
    "lastName": "Baxter",
    "email": "jaime.baxter70@techfactors.com",
    "phone": "09407493694",
    "username": "jaime.baxter",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 71,
    "firstName": "Jack",
    "lastName": "Moore",
    "email": "jack.moore71@techfactors.com",
    "phone": "09266309420",
    "username": "jack.moore",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 72,
    "firstName": "Gabriel",
    "lastName": "Dawson",
    "email": "gabriel.dawson72@techfactors.com",
    "phone": "09548777506",
    "username": "gabriel.dawson",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 73,
    "firstName": "Scott",
    "lastName": "Munoz",
    "email": "scott.munoz73@techfactors.com",
    "phone": "09212224565",
    "username": "scott.munoz",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 74,
    "firstName": "Michael",
    "lastName": "Brown",
    "email": "michael.brown74@techfactors.com",
    "phone": "09739806306",
    "username": "michael.brown",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 75,
    "firstName": "Alicia",
    "lastName": "Mills",
    "email": "alicia.mills75@techfactors.com",
    "phone": "09156791390",
    "username": "alicia.mills",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 76,
    "firstName": "Jennifer",
    "lastName": "Flores",
    "email": "jennifer.flores76@techfactors.com",
    "phone": "09045786981",
    "username": "jennifer.flores",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 77,
    "firstName": "Julia",
    "lastName": "Hardin",
    "email": "julia.hardin77@techfactors.com",
    "phone": "09695992378",
    "username": "julia.hardin",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 78,
    "firstName": "Megan",
    "lastName": "Jenkins",
    "email": "megan.jenkins78@techfactors.com",
    "phone": "09318986223",
    "username": "megan.jenkins",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 79,
    "firstName": "Anthony",
    "lastName": "Hill",
    "email": "anthony.hill79@techfactors.com",
    "phone": "09084246728",
    "username": "anthony.hill",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 80,
    "firstName": "Tiffany",
    "lastName": "Adams",
    "email": "tiffany.adams80@techfactors.com",
    "phone": "09493164048",
    "username": "tiffany.adams",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 81,
    "firstName": "Michelle",
    "lastName": "Garcia",
    "email": "michelle.garcia81@techfactors.com",
    "phone": "09720214177",
    "username": "michelle.garcia",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 82,
    "firstName": "Alexis",
    "lastName": "Bowman",
    "email": "alexis.bowman82@techfactors.com",
    "phone": "09731821075",
    "username": "alexis.bowman",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 83,
    "firstName": "Mark",
    "lastName": "Graham",
    "email": "mark.graham83@techfactors.com",
    "phone": "09724296645",
    "username": "mark.graham",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 84,
    "firstName": "Julia",
    "lastName": "Waters",
    "email": "julia.waters84@techfactors.com",
    "phone": "09471636247",
    "username": "julia.waters",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 85,
    "firstName": "Andrew",
    "lastName": "Spears",
    "email": "andrew.spears85@techfactors.com",
    "phone": "09963651472",
    "username": "andrew.spears",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 86,
    "firstName": "Julie",
    "lastName": "Conrad",
    "email": "julie.conrad86@techfactors.com",
    "phone": "09894123511",
    "username": "julie.conrad",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 87,
    "firstName": "Crystal",
    "lastName": "Long",
    "email": "crystal.long87@techfactors.com",
    "phone": "09643172341",
    "username": "crystal.long",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 88,
    "firstName": "Melissa",
    "lastName": "Torres",
    "email": "melissa.torres88@techfactors.com",
    "phone": "09934737348",
    "username": "melissa.torres",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 89,
    "firstName": "Michael",
    "lastName": "Bonilla",
    "email": "michael.bonilla89@techfactors.com",
    "phone": "09114472953",
    "username": "michael.bonilla",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 90,
    "firstName": "Lindsey",
    "lastName": "Hill",
    "email": "lindsey.hill90@techfactors.com",
    "phone": "09269066704",
    "username": "lindsey.hill",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 91,
    "firstName": "Jennifer",
    "lastName": "Jones",
    "email": "jennifer.jones91@techfactors.com",
    "phone": "09038158856",
    "username": "jennifer.jones",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 92,
    "firstName": "James",
    "lastName": "Jackson",
    "email": "james.jackson92@techfactors.com",
    "phone": "09993589022",
    "username": "james.jackson",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 93,
    "firstName": "Ronald",
    "lastName": "Nguyen",
    "email": "ronald.nguyen93@techfactors.com",
    "phone": "09375328383",
    "username": "ronald.nguyen",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 94,
    "firstName": "Lisa",
    "lastName": "Miller",
    "email": "lisa.miller94@techfactors.com",
    "phone": "09043042372",
    "username": "lisa.miller",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 95,
    "firstName": "Hannah",
    "lastName": "Lewis",
    "email": "hannah.lewis95@techfactors.com",
    "phone": "09471396226",
    "username": "hannah.lewis",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 96,
    "firstName": "Jennifer",
    "lastName": "Elliott",
    "email": "jennifer.elliott96@techfactors.com",
    "phone": "09330309457",
    "username": "jennifer.elliott",
    "department": "Sales",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 97,
    "firstName": "Jason",
    "lastName": "Mathis",
    "email": "jason.mathis97@techfactors.com",
    "phone": "09470456648",
    "username": "jason.mathis",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
  {
    "id": 98,
    "firstName": "Joseph",
    "lastName": "Webb",
    "email": "joseph.webb98@techfactors.com",
    "phone": "09621196917",
    "username": "joseph.webb",
    "department": "Dev",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 99,
    "firstName": "Michael",
    "lastName": "Williams",
    "email": "michael.williams99@techfactors.com",
    "phone": "09490819583",
    "username": "michael.williams",
    "department": "HR/Admin",
    "role": "Employee",
    "password": "12345678",
  },
  {
    "id": 100,
    "firstName": "Bryan",
    "lastName": "Davis",
    "email": "bryan.davis100@techfactors.com",
    "phone": "09405731885",
    "username": "bryan.davis",
    "department": "HR/Admin",
    "role": "HR",
    "password": "12345678",
  },
]